import {
  ConversationChannel,
  ConversationStatus,
  EvaluationStatus,
  InteractionType,
  LeadSourcePrimary,
  LeadStage,
  LeadStatus,
  LeadTemperature,
  LeadUrgency,
  MessageDirection,
  MessageStatus,
  MessageType,
  OpportunityStatus,
  SenderType,
  TaskPriority,
  TaskStatus,
  TaskType,
  UserRole,
  type Conversation,
  type Evaluation,
  type Interaction,
  type Lead,
  type Message,
  type Opportunity,
  type Task,
  type User
} from "@prisma/client";

type DemoUser = Pick<User, "id" | "name" | "email" | "role" | "title" | "isActive"> & { password: string };

export const demoUsers: DemoUser[] = [
  {
    id: "demo-admin",
    name: "Camila Gestora",
    email: "admin@premiumsalescrm.com",
    role: UserRole.ADMIN,
    title: "Diretora Comercial",
    isActive: true,
    password: "12345678"
  },
  {
    id: "demo-seller",
    name: "Bruno Comercial",
    email: "comercial@premiumsalescrm.com",
    role: UserRole.SELLER,
    title: "Executivo Comercial",
    isActive: true,
    password: "12345678"
  }
];

const now = new Date();

export const demoLeads: Lead[] = [
  {
    id: "lead-1",
    fullName: "Mariana Souza",
    phone: "(11) 99888-1122",
    whatsapp: "5511998881122",
    email: "mariana@clinicaglow.com",
    instagram: "@marianaglow",
    company: "Clinica Glow",
    city: "Sao Paulo",
    state: "SP",
    sourcePrimary: LeadSourcePrimary.INSTAGRAM,
    sourceDetail: "Campanha premium",
    source: "Instagram",
    mainInterest: "Consultoria comercial",
    investmentRange: "BETWEEN_10K_25K",
    urgency: LeadUrgency.HIGH,
    notes: "Lead decisora, alto potencial.",
    status: LeadStatus.ACTIVE,
    stage: LeadStage.NEGOTIATION,
    temperature: LeadTemperature.HOT,
    potentialValue: 18000 as never,
    closedValue: null,
    attendedEvaluation: true,
    closedAtEvaluation: false,
    whatsappTemplate: "Oi Mariana, passando para alinhar nossa proposta.",
    lossReason: null,
    createdAt: now,
    updatedAt: now,
    lastInteractionAt: now,
    nextActionAt: new Date(now.getTime() + 86400000),
    ownerId: "demo-admin"
  },
  {
    id: "lead-2",
    fullName: "Ricardo Lima",
    phone: "(21) 97777-3344",
    whatsapp: "5521977773344",
    email: "ricardo@institutovita.com",
    instagram: null,
    company: "Instituto Vita",
    city: "Rio de Janeiro",
    state: "RJ",
    sourcePrimary: LeadSourcePrimary.INDICATION,
    sourceDetail: "Parceiro medico",
    source: "Indicacao",
    mainInterest: "Treinamento da equipe",
    investmentRange: "ABOVE_25K",
    urgency: LeadUrgency.MEDIUM,
    notes: "Aguardando retorno da socia.",
    status: LeadStatus.ACTIVE,
    stage: LeadStage.PROPOSAL_SENT,
    temperature: LeadTemperature.WARM,
    potentialValue: 24000 as never,
    closedValue: null,
    attendedEvaluation: false,
    closedAtEvaluation: false,
    whatsappTemplate: null,
    lossReason: null,
    createdAt: now,
    updatedAt: now,
    lastInteractionAt: now,
    nextActionAt: new Date(now.getTime() + 172800000),
    ownerId: "demo-seller"
  },
  {
    id: "lead-3",
    fullName: "Patricia Menezes",
    phone: "(31) 96666-7788",
    whatsapp: "5531966667788",
    email: null,
    instagram: null,
    company: "Studio Viva",
    city: "Belo Horizonte",
    state: "MG",
    sourcePrimary: LeadSourcePrimary.PAID_TRAFFIC,
    sourceDetail: "Meta Ads",
    source: "Trafego pago",
    mainInterest: "Mentoria de conversao",
    investmentRange: "BETWEEN_3K_10K",
    urgency: LeadUrgency.HIGH,
    notes: "Fechou na avaliacao.",
    status: LeadStatus.WON,
    stage: LeadStage.CLOSED,
    temperature: LeadTemperature.HOT,
    potentialValue: 12500 as never,
    closedValue: 11800 as never,
    attendedEvaluation: true,
    closedAtEvaluation: true,
    whatsappTemplate: null,
    lossReason: null,
    createdAt: now,
    updatedAt: now,
    lastInteractionAt: now,
    nextActionAt: null,
    ownerId: "demo-admin"
  }
];

export const demoInteractions: Interaction[] = [
  {
    id: "interaction-1",
    type: InteractionType.WHATSAPP,
    occurredAt: now,
    content: "Apresentacao inicial enviada.",
    nextActionAt: new Date(now.getTime() + 86400000),
    createdAt: now,
    updatedAt: now,
    leadId: "lead-1",
    userId: "demo-admin"
  },
  {
    id: "interaction-2",
    type: InteractionType.PROPOSAL,
    occurredAt: now,
    content: "Proposta enviada com plano de 90 dias.",
    nextActionAt: new Date(now.getTime() + 172800000),
    createdAt: now,
    updatedAt: now,
    leadId: "lead-2",
    userId: "demo-seller"
  }
];

export const demoTasks: Task[] = [
  {
    id: "task-1",
    title: "Follow-up da proposta Glow",
    description: null,
    dueDate: new Date(now.getTime() + 86400000),
    status: TaskStatus.PENDING,
    type: TaskType.FOLLOW_UP,
    priority: TaskPriority.HIGH,
    createdAt: now,
    updatedAt: now,
    completedAt: null,
    leadId: "lead-1",
    ownerId: "demo-admin"
  },
  {
    id: "task-2",
    title: "Retornar Instituto Vita",
    description: null,
    dueDate: new Date(now.getTime() - 14400000),
    status: TaskStatus.OVERDUE,
    type: TaskType.RETURN,
    priority: TaskPriority.MEDIUM,
    createdAt: now,
    updatedAt: now,
    completedAt: null,
    leadId: "lead-2",
    ownerId: "demo-seller"
  }
];

export const demoOpportunities: Opportunity[] = [
  {
    id: "opp-1",
    title: "Projeto Growth Clinica Glow",
    estimatedValue: 18000 as never,
    finalValue: null,
    status: OpportunityStatus.NEGOTIATING,
    sentAt: now,
    returnAt: new Date(now.getTime() + 172800000),
    notes: "Negociacao final.",
    createdAt: now,
    updatedAt: now,
    leadId: "lead-1",
    ownerId: "demo-admin"
  },
  {
    id: "opp-2",
    title: "Treinamento Instituto Vita",
    estimatedValue: 24000 as never,
    finalValue: null,
    status: OpportunityStatus.SENT,
    sentAt: now,
    returnAt: new Date(now.getTime() + 259200000),
    notes: null,
    createdAt: now,
    updatedAt: now,
    leadId: "lead-2",
    ownerId: "demo-seller"
  }
];

export const demoEvaluations: Evaluation[] = [
  {
    id: "eval-1",
    scheduledAt: new Date(now.getTime() + 86400000),
    status: EvaluationStatus.CONFIRMED,
    attended: null,
    preNotes: "Cliente quer previsibilidade comercial.",
    postNotes: null,
    createdAt: now,
    updatedAt: now,
    leadId: "lead-1",
    ownerId: "demo-admin"
  },
  {
    id: "eval-2",
    scheduledAt: new Date(now.getTime() - 86400000),
    status: EvaluationStatus.COMPLETED,
    attended: true,
    preNotes: "Lead aquecida.",
    postNotes: "Fechou no mesmo dia.",
    createdAt: now,
    updatedAt: now,
    leadId: "lead-3",
    ownerId: "demo-admin"
  }
];

export const demoConversations: Conversation[] = [
  {
    id: "conv-1",
    channel: ConversationChannel.WHATSAPP,
    status: ConversationStatus.BOT_ACTIVE,
    subject: "Qualificacao inicial Glow",
    contactPhone: "5511998881122",
    externalContactId: "wa-contact-1",
    lastMessageAt: now,
    botEnabled: true,
    botHandoffRequested: false,
    createdAt: now,
    updatedAt: now,
    leadId: "lead-1",
    ownerId: "demo-admin"
  },
  {
    id: "conv-2",
    channel: ConversationChannel.WHATSAPP,
    status: ConversationStatus.WAITING_HUMAN,
    subject: "Retorno proposta Vita",
    contactPhone: "5521977773344",
    externalContactId: "wa-contact-2",
    lastMessageAt: new Date(now.getTime() - 3600000),
    botEnabled: true,
    botHandoffRequested: true,
    createdAt: now,
    updatedAt: now,
    leadId: "lead-2",
    ownerId: "demo-seller"
  }
];

export const demoMessages: Message[] = [
  {
    id: "msg-1",
    body: "Oi, quero entender como funciona a consultoria para minha clinica.",
    type: MessageType.TEXT,
    mediaUrl: null,
    mimeType: null,
    fileName: null,
    caption: null,
    durationSeconds: null,
    senderType: SenderType.CUSTOMER,
    direction: MessageDirection.INBOUND,
    status: MessageStatus.READ,
    externalMessageId: "wamid-1",
    metadata: null,
    createdAt: new Date(now.getTime() - 7200000),
    updatedAt: new Date(now.getTime() - 7200000),
    conversationId: "conv-1",
    userId: null
  },
  {
    id: "msg-2",
    body: "Perfeito. Posso te fazer 3 perguntas rapidas para qualificar seu momento comercial?",
    type: MessageType.TEXT,
    mediaUrl: null,
    mimeType: null,
    fileName: null,
    caption: null,
    durationSeconds: null,
    senderType: SenderType.BOT,
    direction: MessageDirection.OUTBOUND,
    status: MessageStatus.DELIVERED,
    externalMessageId: "wamid-2",
    metadata: null,
    createdAt: new Date(now.getTime() - 7100000),
    updatedAt: new Date(now.getTime() - 7100000),
    conversationId: "conv-1",
    userId: null
  },
  {
    id: "msg-3",
    body: "Enviei a proposta para avaliacao. Pode me chamar se quiser ajustar algo.",
    type: MessageType.TEXT,
    mediaUrl: null,
    mimeType: null,
    fileName: null,
    caption: null,
    durationSeconds: null,
    senderType: SenderType.USER,
    direction: MessageDirection.OUTBOUND,
    status: MessageStatus.READ,
    externalMessageId: "wamid-3",
    metadata: null,
    createdAt: new Date(now.getTime() - 3600000),
    updatedAt: new Date(now.getTime() - 3600000),
    conversationId: "conv-2",
    userId: "demo-seller"
  },
  {
    id: "msg-4",
    body: "Quero falar com alguem antes de decidir.",
    type: MessageType.TEXT,
    mediaUrl: null,
    mimeType: null,
    fileName: null,
    caption: null,
    durationSeconds: null,
    senderType: SenderType.CUSTOMER,
    direction: MessageDirection.INBOUND,
    status: MessageStatus.READ,
    externalMessageId: "wamid-4",
    metadata: null,
    createdAt: new Date(now.getTime() - 3500000),
    updatedAt: new Date(now.getTime() - 3500000),
    conversationId: "conv-2",
    userId: null
  },
  {
    id: "msg-5",
    body: "",
    type: MessageType.AUDIO,
    mediaUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    mimeType: "audio/mpeg",
    fileName: "qualificacao.mp3",
    caption: null,
    durationSeconds: 18,
    senderType: SenderType.CUSTOMER,
    direction: MessageDirection.INBOUND,
    status: MessageStatus.READ,
    externalMessageId: "wamid-5",
    metadata: null,
    createdAt: new Date(now.getTime() - 2400000),
    updatedAt: new Date(now.getTime() - 2400000),
    conversationId: "conv-2",
    userId: null
  },
  {
    id: "msg-6",
    body: "",
    type: MessageType.IMAGE,
    mediaUrl: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80",
    mimeType: "image/jpeg",
    fileName: "clinica.jpg",
    caption: "Essa e a fachada da clinica.",
    durationSeconds: null,
    senderType: SenderType.CUSTOMER,
    direction: MessageDirection.INBOUND,
    status: MessageStatus.READ,
    externalMessageId: "wamid-6",
    metadata: null,
    createdAt: new Date(now.getTime() - 1800000),
    updatedAt: new Date(now.getTime() - 1800000),
    conversationId: "conv-1",
    userId: null
  },
  {
    id: "msg-7",
    body: "",
    type: MessageType.VIDEO,
    mediaUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    mimeType: "video/mp4",
    fileName: "avaliacao.mp4",
    caption: "Video curto mostrando o espaco da avaliacao.",
    durationSeconds: 12,
    senderType: SenderType.USER,
    direction: MessageDirection.OUTBOUND,
    status: MessageStatus.DELIVERED,
    externalMessageId: "wamid-7",
    metadata: null,
    createdAt: new Date(now.getTime() - 900000),
    updatedAt: new Date(now.getTime() - 900000),
    conversationId: "conv-1",
    userId: "demo-admin"
  }
];
